---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: nginx-{{ .Chart.Name }}
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: {{ .Values.containerPort }}
